name: Build Native Image and Publish Release

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.1'
          java-version: '19'

      - name: Install musl and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools zlib1g-dev
          sudo apt-get install -y musl-dev
          mkdir -p /tmp/zlib-musl
          cd /tmp/zlib-musl
          wget https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.gz
          tar -xzf zlib-1.3.1.tar.gz
          cd zlib-1.3.1
          CC=musl-gcc ./configure --static --prefix=/usr/local/musl
          make
          sudo make install
          sudo ln -s /usr/local/musl/lib/libz.a /usr/lib/x86_64-linux-musl/libz.a

      - name: Build native image with Maven and musl
        run: |
          ./mvnw -Pnative-musl package

      - name: Compress binary
        run: |
          tar -czvf easy-proxy-linux-x86_64.tar.gz -C target easy-proxy

      - name: Create release and attach artifact
        uses: softprops/action-gh-release@v2
        with:
          files: easy-proxy-linux-x86_64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
